Repository Nice-HUD/Spacebar, pull requests merged in 2024-12, with the labels that each got.

#25 [#96] 스킨 선택 기능 구현
  src/main/java/engine/Core.java
  src/main/java/engine/DrawManager.java
  src/main/java/engine/FileManager.java
  src/main/java/screen/SkinSelectionScreen.java
  src/main/java/screen/TitleScreen.java
  src/main/resources/shipGraphics
  src/test/java/screen/SkinSelectionScreenTest.java
  src/test/resources/shipGraphics
Labels: D-1

#27 JaCoCo 커버리지 - Github Action(CI) 연동
  .github/workflows/main.yml
  src/main/java/entity/SubShip.java
  src/test/java/entity/SubShipTest.java
Labels: D-0

#26 [#64] 소리 조절 기능 구현
  src/main/java/engine/Core.java
  src/main/java/engine/DrawManager.java
  src/main/java/engine/SoundManager.java
  src/main/java/screen/SettingsScreen.java
  src/test/java/screen/SettingsScreenTest.java
  src/test/java/screen/SoundControlTest.java
Labels: D-0

#29 [#29] 빌드 실패 해결
  src/main/java/engine/SoundManager.java
  src/test/java/screen/SelectLevelTest.java
  src/test/java/screen/SettingsScreenTest.java
  src/test/java/screen/SoundControlTest.java
Labels: D-3

#28 [#95] 테마 색상 변경 기능 구현
  src/main/java/engine/DrawManager.java
  src/main/java/screen/SettingsScreen.java
  src/test/java/screen/SettingsScreenTest.java
Labels: D-2

#30 [배포 준비] v1.1 릴리즈
  .github/workflows/Slack_on_PR.yml
  .github/workflows/code_review_from_chatgpt.yml
  .github/workflows/main.yml
  .github/workflows/notify-line-count.yml
  .gitignore
  README.md
  application.properties
  build.gradle
  src/main/java/engine/Core.java
  src/main/java/engine/DrawManager.java
  src/main/java/engine/FileManager.java
  src/main/java/engine/Frame.java
  src/main/java/engine/SoundManager.java
  src/main/java/entity/EnemyShip.java
  src/main/java/entity/EnemyShipFormation.java
  src/main/java/entity/SubShip.java
  src/main/java/screen/GameScreen.java
  src/main/java/screen/Screen.java
  src/main/java/screen/SettingsScreen.java
  src/main/java/screen/SkinSelectionScreen.java
  src/main/java/screen/TitleScreen.java
  src/main/resources/shipGraphics
  src/test/java/entity/EnemyShipFormationTest.java
  src/test/java/entity/SubShipTest.java
  src/test/java/screen/FrameTest.java
  src/test/java/screen/GameScreenTest.java
  src/test/java/screen/PauseTest.java
  src/test/java/screen/SelectLevelTest.java
  src/test/java/screen/SettingsScreenTest.java
  src/test/java/screen/SkinSelectionScreenTest.java
  src/test/java/screen/SoundControlTest.java
  src/test/resources/shipGraphics
Labels: D-0
