Repository Nice-HUD/Spacebar, pull requests merged in 2024-11, with the labels that each got.

#8 보조 비행기 기능 구현
  .github/workflows/Slack_on_PR.yml
  log
  log.1
  src/main/java/engine/DrawManager.java
  src/main/java/entity/Ship.java
  src/main/java/entity/SubShip.java
  src/main/java/screen/GameScreen.java
  src/main/resources/graphics
  src/test/java/SubShipTest.java
Labels: enhancement

#7 2인용 게임 내 오류 수정
  .gitignore
  log
  log.1
  src/main/java/engine/Core.java
  src/main/java/engine/GameState.java
  src/main/java/entity/Ship.java
  src/main/java/screen/GameScreen.java
  src/main/java/screen/ScoreScreen.java
Labels: bug

#9 fix: 버그 해결
  src/main/java/screen/GameScreen.java
Labels: bug

#11 설정 화면 구현 - 메인 메뉴
  build.gradle
  src/main/java/engine/Core.java
  src/main/java/engine/DrawManager.java
  src/main/java/screen/SettingsScreen.java
  src/main/java/screen/TitleScreen.java
  src/test/java/entity/SubShipTest.java
  src/test/java/screen/SettingsScreenTest.java
Labels: enhancement

#14 ci : PR관련 자동화 및 slack알람 구현(1)
  .github/workflows/d-day-labeler.yml
  .github/workflows/notify-line-count.yml
  .github/workflows/simple-labeler.yml
Labels: D-3

#16 ci : PR목록 slack알림 구현
  .github/scripts/pr_reminder.py
  .github/workflows/pr-review-reminder.yml
Labels: D-3

#15 빌드 에러 해결하기 위한 test코드 수정
  src/test/java/entity/SubShipTest.java
  src/test/java/screen/SettingsScreenTest.java
Labels: D-2

#18 [#101] 빌드 에러 해결을 위한 jdk 버전 고정
  build.gradle
Labels: D-1

#17 [#53]레벨 선택 기능 구현
  src/main/java/engine/Core.java
  src/main/java/engine/DrawManager.java
  src/main/java/engine/GameState.java
  src/main/java/screen/ReceiptScreen.java
  src/main/java/screen/TitleScreen.java
  src/test/java/screen/SelectLevelTest.java
Labels: D-0

#19 [#104] pause - restart 시 레벨 유지
  src/main/java/engine/Core.java
  src/test/java/screen/PauseTest.java
Labels: D-2

#22 [#97] 적 함선이 맨 아래쪽 화면에 도달했을 때 게임 오버
  src/main/java/entity/EnemyShip.java
  src/main/java/entity/EnemyShipFormation.java
  src/main/java/screen/GameScreen.java
  src/test/java/entity/EnemyShipFormationTest.java
  src/test/java/screen/GameScreenTest.java
Labels: D-2

#23 [#87] 동적 코드 분석을 위한 Sentry 도입
  .gitignore
  build.gradle
  src/main/java/engine/Core.java
Labels: D-1

#24 [#102] pause test 코드 개선 및 pause 관련 메서드 주석 처리
  src/main/java/screen/GameScreen.java
  src/test/java/screen/PauseTest.java
Labels: D-1
